# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.Version={{.Version}}'
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - '386'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: arm64
    binary: '{{ .ProjectName }}'
archives:
  - format: tar.gz # default
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
# If you want to manually examine the release before its live, uncomment this line:
 draft: true
changelog:
  skip: false
