name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      -
        name: Go Build
        run: go build -v ./...

      -
        name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      -
        name: GoReleaser Check
        run: goreleaser check

      -
        name: Diff
        run: git diff

      -
        name: GoReleaser
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            goreleaser
          elif [[ $GITHUB_REF == refs/heads/master ]]; then
            goreleaser --snapshot
          fi
