name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3

    -
      name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    -
      name: Go Build
      run: go build -v ./...

    -
      name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        install-only: true

    -
      name: GoReleaser Check
      run: goreleaser check

    -
      name: Diff
      run: git diff

    -
      name: GoReleaser
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          goreleaser
        elif [[ $GITHUB_REF == refs/heads/master ]]; then
          goreleaser --snapshot
        fi