name: gofmt

on: [pull_request]

jobs:
  gofmt:
    name: gofmt
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: reviewdog / gofmt
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: '--disable-all -E gofmt,goimports'
          fail_on_error: true
          level: error
          reporter: github-pr-review
          filter_mode: file